// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjA4Q3KyQrmhTBFNWJ5kaj76OQ0WF25p8',
    appId: '1:29873352798:web:cf7b212dfa69a5116ac4cf',
    messagingSenderId: '29873352798',
    projectId: 'flutter-fire-demo-app',
    authDomain: 'flutter-fire-demo-app.firebaseapp.com',
    storageBucket: 'flutter-fire-demo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JeCbmNT7cN8VZdS-GywedHnCoU6wG1E',
    appId: '1:29873352798:android:c1542a3f903488df6ac4cf',
    messagingSenderId: '29873352798',
    projectId: 'flutter-fire-demo-app',
    storageBucket: 'flutter-fire-demo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxMFjry-ScjzSqy8lfrD_xrYkCPaNN2QY',
    appId: '1:29873352798:ios:68f39444d1e1d1696ac4cf',
    messagingSenderId: '29873352798',
    projectId: 'flutter-fire-demo-app',
    storageBucket: 'flutter-fire-demo-app.appspot.com',
    iosClientId: '29873352798-terp4di6csaue91cg18rhbum5vc4ubif.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxMFjry-ScjzSqy8lfrD_xrYkCPaNN2QY',
    appId: '1:29873352798:ios:68f39444d1e1d1696ac4cf',
    messagingSenderId: '29873352798',
    projectId: 'flutter-fire-demo-app',
    storageBucket: 'flutter-fire-demo-app.appspot.com',
    iosClientId: '29873352798-terp4di6csaue91cg18rhbum5vc4ubif.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
